import {
  faTimes,
  faBars,
  faExchangeAlt,
  faTrafficLightGo,
  faHeart,
  faImages,
  faTags,
  faClock,
  faTrashAlt,
  faPlusCircle,
  faBriefcase,
  faSignOut,
  faHandshake,
  faAngleDoubleUp,
  faStepForward,
  faPhone,
  faEnvelope,
  faCheckCircle,
  faDoorOpen,
  faBackspace,
  faPlus,
  faSyncAlt,
  faBox,
  faRedo,
  faSortAlphaDown,
  faPlaneArrival,
  faHouseReturn,
  faCheck,
  faIdBadge,
  faCalendarTimes,
  faLongArrowDown,
  faHouseUser,
  faLocation,
  faHamburger,
} from '@fortawesome/pro-regular-svg-icons'

import {
  faLinkedin,
  faFacebook,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons'

import {
  faRocket,
  faTrafficLightGo as faslAngleDoubleUp,
  faArrowCircleRight as fasArrowCircleRight,
  faArrowCircleLeft as fasArrowCircleLeft,
  faChevronRight as fasChevronRight,
  faChevronDown as fasChevronDown,
  faHeart as fasHeart,
  faDoNotEnter as fasDoNotEnter,
} from '@fortawesome/pro-solid-svg-icons'

export const iconspro = [
  faRocket,
  faTimes,
  faBars,
  faExchangeAlt,
  faTrafficLightGo,
  faslAngleDoubleUp,
  faHeart,
  faImages,
  faTags,
  faClock,
  faTrashAlt,
  fasArrowCircleRight,
  fasChevronRight,
  fasChevronDown,
  faPlusCircle,
  fasHeart,
  faBriefcase,
  faSignOut,
  faHandshake,
  faAngleDoubleUp,
  faStepForward,
  faPhone,
  faEnvelope,
  fasDoNotEnter,
  fasArrowCircleLeft,
  faCheckCircle,
  faDoorOpen,
  faBackspace,
  faPlus,
  faSyncAlt,
  faBox,
  faRedo,
  faSortAlphaDown,
  faPlaneArrival,
  faHouseReturn,
  faCheck,
  faIdBadge,
  faCalendarTimes,
  faLongArrowDown,
  faHouseUser,
  faLinkedin,
  faFacebook,
  faTwitter,
  faLocation,
  faHamburger,
]
